/**
 * Generates src/app/generated/icons.ts from src/app/assets/icons/*.svg.
 * Run with: bun scripts/gen-icons.ts
 */
import {readdirSync, readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {join} from 'node:path';

const iconsDir = join(__dirname, '../src/app/assets/icons');
const outDir = join(__dirname, '../src/app/generated');
const outFile = join(outDir, 'icons.ts');

const names = readdirSync(iconsDir)
  .filter(f => f.endsWith('.svg'))
  .map(f => f.replace(/\.svg$/, ''))
  .sort();

const entries = names
  .map(n => {
    const xml = readFileSync(join(iconsDir, `${n}.svg`), 'utf-8');
    const raw = JSON.stringify(xml);
    return `  ${/^[a-z0-9]+$/i.test(n) ? n : JSON.stringify(n)}: ${raw},`;
  })
  .join('\n');

mkdirSync(outDir, {recursive: true});
writeFileSync(
  outFile,
  `/* Generated by scripts/gen-icons.ts. Do not edit manually. */\nexport const icons = {\n${entries}\n} as const;\n`,
);

console.log(`generated ${names.length} icons -> ${outFile}`);
