import {aesEcbDecrypt, md5Hex} from '@/core/crypto';

describe('crypto md5Hex', () => {
  it('matches reference values', () => {
    expect(md5Hex('')).toBe('d41d8cd98f00b204e9800998ecf8427e');
    expect(md5Hex('abc')).toBe('900150983cd24fb0d6963f7d28e17f72');
    expect(md5Hex('10020000001')).toBe(md5Hex('10020000001'));
  });
});

describe('crypto aesEcbDecrypt', () => {
  it('decrypts sample generated by openssl (AES-256-ECB, PKCS7)', () => {
    const ts = '1699999999';
    const secret = '185Hcomic3PAPP7R';
    const data = 'KHE/NhGMlHfXM4ewpz2UT98bgZKyElcYVfGNY/2L4fQ=';
    expect(aesEcbDecrypt(data, `${ts}${secret}`)).toBe('{"id":100200,"name":"test"}');
  });
});
